### ISSUE TITLE
Lightcycle: Option for increased thumb curvature

### ISSUE THREAD

**Issue by jgandert** [ibnuda/dactyl-keyboard#14]
It seems like an increased curvature (so farthest away keys come nearer) for the thumb cluster could be beneficial for reducing strain and avoiding accidental keypresses:

![dmote020_thumb](https://user-images.githubusercontent.com/3063858/84435423-180bf300-ac32-11ea-85cb-2b7603c75368.jpg)

This is the DMOTE keyboard: [veikman/dactyl-keyboard](https://github.com/veikman/dactyl-keyboard) (Dactyl variation)
*(Image source (screenshot from video): https://viktor.eikman.se/article/the-dmote/)*

**Comment by CreamyCookie** [comment]
Small edit (blue bars):



Similar to what is already the case with the main keys' curvature this would reduce the distance for the thumbs to travel.

Of course, keys would also have to be farther apart so that keycaps are still the same distance (as in the main key area), so it would result in a larger thumb cluster.

**Comment by jgandert** [comment]
Small edit:

![thumb curvature option 3](https://user-images.githubusercontent.com/3063858/84822186-94307d00-b01c-11ea-88f4-9fab37e5598d.png)



Similar to what is already the case with the main keys' curvature this would reduce the distance for the thumbs to travel.

Of course, key sockets would also have to be a bit farther apart so that keycaps are still the same distance (as in the main key area), so it would result in a larger thumb cluster.

**Comment by jgandert** [comment]
@ibnuda Thank you!
