### ISSUE TITLE
Manuform: 6th row key caps get stuck against case when using column stagger

### ISSUE THREAD

**Issue by dereknheiley** [ibnuda/dactyl-keyboard#45]
Keys, 8 and 9 (and 2 and 3) just barely have clearance, and keys F8 and F9 (and F2 and F3) rub and get stuck against the case on a 6th row when column stagger is used.

Suggest enforcing minimum clearance around keys, and forcing outer three columns to fan out slightly at the top to ensure minimum wall thickness is maintained.

![dm-red-2tight-clearance](https://user-images.githubusercontent.com/3382160/87492744-4017b900-c619-11ea-9bf1-5faaabf9d8f2.jpg)

**Comment by jgandert** [comment]
I could be mistaken, but I think that's related to #39 (which I opened). The vertical center of the curvature seems to be at the top (rather than somewhere in the middle) and thus causes the keys to collide at that point. 

Of course, one could just increase the distance at the top, but I'm not sure if that would be preferable, given that the goal for ergonomics usually is to reduce unnecessary finger movement.

**Comment by dereknheiley** [comment]
Ah, i'm realizing now (poking through the code trying to fix it myself) that the problem is because the underlying geometry i want is impossible. IE: you can't have a very deep row curve, and not run into collisions like this on the first and last rows of the columns when using aggressive column stagger / recess. At least not on keyboards with curved columns. 
![row-curvature-affect-on-top-row](https://user-images.githubusercontent.com/3382160/88748327-c3a7ce80-d11e-11ea-83fe-c1492c1b32e5.png)

**Comment by jgandert** [comment]
Yes, that's true, but again, it seems to me that at least in many cases, the collision is caused by the "Center of the curvature for the row" being at the top, not the y-center, no?

Again, maybe I'm mistaken, but at least I don't see why else here on the right the collision is at the top.

![](https://user-images.githubusercontent.com/3063858/86954985-2678fc00-c157-11ea-8dc8-28343c464289.png)

Of course, it's possible that if the center was different it would instead collide at both the top and bottom
